/*
 *
 *  Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ultrasonic driver
 *
 * Created on: Jun 2, 2022
 *
 * Author: MAHMOUD EL-FEKY
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* Ultrasonic Pins Ids */
#define ULTRASONIC_TRIG_PORT_ID                 PORTB_ID
#define ULTRASONIC_TRIG_PIN_ID                	PIN5_ID
#define ULTRASONIC_ECHO_PORT_ID					PORTD_ID
#define ULTRASONIC_ECHO_ID						PIN6_ID

#define ULTRASONIC_TRIG_DELAY                 	10
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the Ultrasonic sensor:
 * Description
 * 1- Initialize the ICU driver as required.
 * 2- Setup the ICU call back function.
 * 3- Setup the direction for the trigger pin as output pin through the GPIO driver.
 * Inputs: None
 * Return: None
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 * Inputs: None
 * Return: None
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Inputs: None.
 * Return: The measured distance in Centimeter.
 */

uint16 Ultrasonic_readDistance(void);

/*
 *  Description:
 *  This is the call back function called by the ICU driver.
 *  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *  Inputs: None
 *  Return: None
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
